import { useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { X } from 'lucide-react';
import { api, validateBenchmark, validateTarget, type Snapshot } from './domain';
export function ActionDialog({ kind, snapshot, refresh, disabled }: { kind: 'target' | 'benchmark'; snapshot?: Snapshot; refresh: () => void; disabled: boolean }) {
  const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const v = (key: string) => String(f.get(key) ?? ''); const validation = kind === 'target' ? validateTarget(v('url'), v('name')) : validateBenchmark(v('concurrency'), Number(v('duration')), Number(v('maxTokens'))); if (validation) { setError(validation); return; } if (kind === 'benchmark' && (!v('targetId') || !v('model') || !v('prompt').trim())) { setError('Choose a target, model, and enter a prompt.'); return; } setBusy(true); setError(''); try { await api(kind === 'target' ? '/targets' : '/benchmarks', { method: 'POST', body: JSON.stringify(kind === 'target' ? { name: v('name'), engine: v('engine'), url: v('url'), metricsUrl: v('metricsUrl') || undefined, apiKeyEnv: v('apiKeyEnv') || undefined } : { name: v('name'), targetId: v('targetId'), model: v('model'), prompt: v('prompt'), concurrency: v('concurrency').split(',').map(Number), durationSeconds: Number(v('duration')), maxTokens: Number(v('maxTokens')) }) }); setOpen(false); refresh(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className={kind === 'benchmark' ? 'primary' : 'secondary'} disabled={disabled}>{kind === 'benchmark' ? '↗ Run benchmark' : '+ Add target'}</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog"><Dialog.Title>{kind === 'target' ? 'Connect an inference target' : 'Launch a benchmark'}</Dialog.Title><Dialog.Description>{kind === 'target' ? 'Connect an OpenAI-compatible HTTP endpoint. Credentials remain in environment variables.' : 'Measure real streamed requests with a bounded concurrency sweep. Prompt text is not stored.'}</Dialog.Description><Dialog.Close className="dialog-close" aria-label="Close dialog"><X size={18} /></Dialog.Close><form onSubmit={submit}><label>Name<input name="name" required={kind === 'target'} placeholder={kind === 'target' ? 'Local vLLM' : 'Concurrency sweep'} /></label>{kind === 'target' ? <><label>Engine<select name="engine">{['vllm', 'sglang', 'tensorrt-llm', 'triton', 'llama.cpp', 'ollama', 'tgi', 'openai'].map(engine => <option key={engine}>{engine}</option>)}</select></label><label>Endpoint URL<input name="url" placeholder="http://localhost:8000" required /></label><label>Metrics URL <span>(optional)</span><input name="metricsUrl" placeholder="http://localhost:8000/metrics" /></label><label>API key environment variable <span>(optional)</span><input name="apiKeyEnv" placeholder="INFERENCE_API_KEY" /></label></> : <><label>Target<select name="targetId" required><option value="">Select a target</option>{snapshot?.targets.map(target => <option key={target.id} value={target.id}>{target.name}</option>)}</select></label><label>Model<input name="model" list="model-options" placeholder="Model identifier" required /><datalist id="model-options">{snapshot?.models.map(model => <option key={`${model.targetId}-${model.id}`} value={model.id} />)}</datalist></label><label>Prompt<textarea name="prompt" rows={3} required placeholder="Explain the purpose of GPU memory bandwidth." /></label><div className="form-grid"><label>Concurrency<input name="concurrency" defaultValue="1,2,4,8" required /></label><label>Duration / point (s)<input name="duration" type="number" min="1" max="3600" defaultValue="30" required /></label></div><label>Maximum output tokens<input name="maxTokens" type="number" min="1" max="32768" defaultValue="256" required /></label></>}{error && <p role="alert" className="error">{error}</p>}<div className="dialog-actions"><Dialog.Close asChild><button type="button" className="secondary">Cancel</button></Dialog.Close><button className="primary" disabled={busy}>{busy ? 'Submitting…' : kind === 'target' ? 'Connect target' : 'Start benchmark'}</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
