export interface Target { id: string; name: string; engine: string; url: string; model?: string; status?: string; error?: string; metricsUrl?: string; apiKeyEnv?: string }
export interface Model { id: string; targetId: string; engine: string }
export interface GPU { index: number; uuid: string; name: string; source: string; utilization?: number; memoryUsedMB?: number; memoryTotalMB?: number; temperatureC?: number; powerW?: number; smClockMHz?: number; pcieRxMBs?: number; pcieTxMBs?: number; eccErrors?: number; xidErrors?: number }
export interface RequestResult { id: string; targetId: string; model: string; startedAt: string; durationMs: number; ttftMs?: number; tpotMs?: number; outputTokens?: number; status: string; error?: string; concurrency?: number }
export interface Finding { kind: string; severity: string; confidence: string; summary: string; evidence: string[]; recommendation: string }
export interface Point { concurrency: number; requests: number; errors: number; rps: number; outputTokensPerSecond?: number; ttft?: { p50?: number; p95?: number }; e2e?: { p50?: number; p95?: number } }
export interface Run { id: string; name?: string; targetId: string; model: string; startedAt: string; status: string; points: Point[]; findings: Finding[]; knee?: number; config?: unknown }
export interface HistoryPoint { time: string; tokensPerSecond?: number; rps?: number; ttftMs?: number; gpuUtilization?: number; kvCachePercent?: number }
export interface Snapshot { time: string; mode: string; targets: Target[]; models: Model[]; gpus: GPU[]; requests: RequestResult[]; runs: Run[]; findings: Finding[]; history: HistoryPoint[]; collectorErrors: string[]; metrics: Record<string, unknown>; system: Record<string, unknown> }
export const routes = ['Overview', 'Models', 'Requests', 'GPUs', 'Benchmarks', 'Experiments', 'System'] as const;
export function metric(value: unknown, unit = '', digits = 1): string { return typeof value === 'number' && Number.isFinite(value) ? `${value.toLocaleString(undefined, { maximumFractionDigits: digits })}${unit ? ` ${unit}` : ''}` : '—'; }
export function validateTarget(url: string, name: string): string | undefined { if (!name.trim()) return 'Enter a target name.'; try { const parsed = new URL(url); if (!['http:', 'https:'].includes(parsed.protocol) || parsed.username || parsed.password) return 'Use an HTTP(S) endpoint without embedded credentials.'; } catch { return 'Enter a valid HTTP(S) endpoint.'; } }
export function validateBenchmark(concurrency: string, duration: number, maxTokens: number): string | undefined { const values = concurrency.split(',').map(Number); if (!values.length || values.length > 16 || values.some(v => !Number.isInteger(v) || v < 1 || v > 256)) return 'Concurrency must contain 1–16 integers between 1 and 256.'; if (new Set(values).size !== values.length) return 'Concurrency points must be unique.'; if (!Number.isInteger(duration) || duration < 1 || duration > 3600) return 'Duration must be between 1 and 3600 seconds.'; if (!Number.isInteger(maxTokens) || maxTokens < 1 || maxTokens > 32768) return 'Maximum tokens must be between 1 and 32768.'; }
export async function api<T>(path: string, options?: RequestInit): Promise<T> { const token = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem('gpup-token') : null; const response = await fetch(`/api/v1${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options?.headers } }); if (!response.ok) { let detail = ''; try { const body = await response.json(); detail = typeof body.error === 'string' ? body.error : ''; } catch { /* HTTP status remains available. */ } throw new Error(detail || `API returned ${response.status} ${response.statusText}`); } if (response.status === 204) return undefined as T; return response.json(); }
