import { useMemo, useRef, useState } from 'react';
import { flexRender, getCoreRowModel, getFilteredRowModel, getSortedRowModel, useReactTable, type ColumnDef, type SortingState } from '@tanstack/react-table';
import { useVirtualizer } from '@tanstack/react-virtual';
import { metric, type RequestResult } from './domain';
export function Requests({ requests }: { requests: RequestResult[] }) {
  const [filter, setFilter] = useState(''); const [sorting, setSorting] = useState<SortingState>([]); const parent = useRef<HTMLDivElement>(null);
  const columns = useMemo<ColumnDef<RequestResult>[]>(() => [{ accessorKey: 'id', header: 'REQUEST', cell: c => <span className="mono">{String(c.getValue()).slice(0, 16)}</span> }, { accessorKey: 'model', header: 'MODEL' }, { accessorKey: 'startedAt', header: 'STARTED', cell: c => new Date(String(c.getValue())).toLocaleTimeString() }, { accessorKey: 'ttftMs', header: 'TTFT', cell: c => metric(c.getValue(), 'ms') }, { accessorKey: 'tpotMs', header: 'TPOT', cell: c => metric(c.getValue(), 'ms') }, { accessorKey: 'durationMs', header: 'END TO END', cell: c => metric(c.getValue(), 'ms', 0) }, { accessorKey: 'outputTokens', header: 'TOKENS', cell: c => metric(c.getValue(), '', 0) }, { accessorKey: 'status', header: 'STATUS', cell: c => <span className={`badge ${c.getValue() === 'error' ? 'warning' : ''}`}>{String(c.getValue())}</span> }], []);
  const table = useReactTable({ data: requests, columns, state: { globalFilter: filter, sorting }, onGlobalFilterChange: setFilter, onSortingChange: setSorting, getCoreRowModel: getCoreRowModel(), getFilteredRowModel: getFilteredRowModel(), getSortedRowModel: getSortedRowModel() });
  const rows = table.getRowModel().rows; const virtual = useVirtualizer({ count: rows.length, getScrollElement: () => parent.current, estimateSize: () => 45, overscan: 10 });
  return <section className="panel"><div className="panel-heading"><div><h2>Request trace</h2><p>Stream timing metadata · {rows.length} requests</p></div><input aria-label="Filter requests" placeholder="Filter requests…" value={filter} onChange={e => setFilter(e.target.value)} /></div><div ref={parent} className="table-scroll"><table><thead>{table.getHeaderGroups().map(group => <tr key={group.id}>{group.headers.map(header => <th key={header.id}><button onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}{header.column.getIsSorted() ? ' ↓' : ''}</button></th>)}</tr>)}</thead><tbody><tr aria-hidden="true" style={{ height: virtual.getVirtualItems()[0]?.start ?? 0 }}><td colSpan={8} /></tr>{virtual.getVirtualItems().map(item => { const row = rows[item.index]; return <tr key={row.id} title={row.original.error}>{row.getVisibleCells().map(cell => <td key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>; })}<tr aria-hidden="true" style={{ height: Math.max(0, virtual.getTotalSize() - (virtual.getVirtualItems().at(-1)?.end ?? 0)) }}><td colSpan={8} /></tr></tbody></table>{!rows.length && <div className="empty">No matching requests. Run a benchmark to collect streamed request timings.</div>}</div><div className="panel-footer">TTFT: first content arrival · TPOT requires authoritative output token usage · Chunk gaps are not token latency</div></section>;
}
